apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: n8h0wju5c-python
  janus-idp.io/tekton: n8h0wju5c-python
  backstage.io/kubernetes-id: n8h0wju5c-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n8h0wju5c-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
