apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: n8h0wju5c-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: n8h0wju5c-python 
  name: n8h0wju5c-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: n8h0wju5c-python 
